### ISSUE TITLE
Merge checklist

### ISSUE THREAD

**Issue by jstolarek** [jstolarek/ghc#113]
- [x] Mention in the commit message that Maybe is now wired-in
- [x] Set the tests field on Trac to point to all the tests in the testsuite
- [x] Read the whole patch once again
- [x] Remove redundant `DataKinds`
