### ISSUE TITLE
Update source code documentation

### ISSUE THREAD

**Issue by jstolarek** [jstolarek/ghc#133]
The source code documentation has not updated since I implemented the changes described in the paper.
- [x] haddockify implementation of U
- [ ] describe algorithm in a note
- [ ] update other notes
- [ ] update the user's guide
