### ISSUE TITLE
Make sure that the documentation includes all the important conlusions

### ISSUE THREAD

**Issue by jstolarek** [jstolarek/ghc#87]
- [x] #68 - Come up with a good injectivity story for PolyKinds
- [x] #75 - Allow self-recursion for injective type families
- [x] #85 - What happens if RHSs contain type families but are identical?

**Comment by jstolarek** [comment]
Relevant notes in the source code:

Note [Environment of injectivity declarations]
Note [Injectivity check for open type families]
Note [Injective type families]
Note [Renaming injectivity declaration]
Note [Skipping injectivity check for empty environments]
