### ISSUE TITLE
Submit the patch and have it acccepted

### ISSUE THREAD

**Issue by jstolarek** [jstolarek/ghc#9]
This ticket is a reminder of things to do when submitting the patch. The current list includes:
- [x] rebase on top of the latest HEAD
- [x] squash all commits into one
- [x] provide a meaningful description of changes, design decisions, etc. Link to the wiki
- [ ] validate in the ghc-validate tree
- [ ] push patches
